/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oodjassignment;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author K15H3N
 */
public class AHHASC_Manager extends javax.swing.JFrame {
    
    public void setUsername(String uname){
        greeting.setText("Welcome Back " + uname +"!");
    }
    
    public AHHASC_Manager() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    oodjassignment.AppointmentForm appointmentTab = new oodjassignment.AppointmentForm();
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MDIparent = new javax.swing.JTabbedPane();
        home = new javax.swing.JPanel();
        greeting = new javax.swing.JLabel();
        userPane = new javax.swing.JButton();
        appointmentPane = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        oodjassignment.AppointmentForm appointment;
        appointment = appointmentTab;
        //oodjassignment.customer user;
        user = null; //new oodjassignment.customer();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("AHHASC");
        setBackground(new java.awt.Color(225, 226, 180));
        setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 10)); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        MDIparent.setBackground(new java.awt.Color(225, 226, 180));
        MDIparent.setForeground(new java.awt.Color(226, 38, 88));
        MDIparent.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);
        MDIparent.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        MDIparent.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 16)); // NOI18N
        MDIparent.setPreferredSize(new java.awt.Dimension(900, 600));
        MDIparent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MDIparentMouseClicked(evt);
            }
        });

        home.setBackground(new java.awt.Color(225, 226, 188));
        home.setForeground(new java.awt.Color(226, 38, 88));
        home.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N

        greeting.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        greeting.setForeground(new java.awt.Color(226, 38, 88));
        greeting.setText("Welcome Back!");

        userPane.setBackground(new java.awt.Color(226, 38, 88));
        userPane.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        userPane.setForeground(new java.awt.Color(255, 255, 255));
        userPane.setText("Manage Users");
        userPane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userPaneActionPerformed(evt);
            }
        });

        appointmentPane.setBackground(new java.awt.Color(226, 38, 88));
        appointmentPane.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        appointmentPane.setForeground(new java.awt.Color(255, 255, 255));
        appointmentPane.setText("Manage Appointments");
        appointmentPane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appointmentPaneActionPerformed(evt);
            }
        });

        logoutButton.setBackground(new java.awt.Color(226, 38, 88));
        logoutButton.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        logoutButton.setForeground(new java.awt.Color(255, 255, 255));
        logoutButton.setText("Log Out");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout homeLayout = new javax.swing.GroupLayout(home);
        home.setLayout(homeLayout);
        homeLayout.setHorizontalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeLayout.createSequentialGroup()
                .addGroup(homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(homeLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(greeting, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(homeLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(logoutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(userPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(appointmentPane, javax.swing.GroupLayout.DEFAULT_SIZE, 741, Short.MAX_VALUE))))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        homeLayout.setVerticalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(greeting, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addComponent(appointmentPane, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(userPane, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(206, Short.MAX_VALUE))
        );

        greeting.getAccessibleContext().setAccessibleName("");

        MDIparent.addTab("Home", home);

        appointment.setBackground(new java.awt.Color(225, 226, 188));
        appointment.setForeground(new java.awt.Color(226, 38, 88));
        MDIparent.addTab("Appointments", appointment);

        //user.setBackground(new java.awt.Color(225, 226, 188));
        //user.setForeground(new java.awt.Color(226, 38, 88));
        MDIparent.addTab("Users", user);

        MDIparent.setSelectedComponent(home);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MDIparent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MDIparent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        MDIparent.getAccessibleContext().setAccessibleName("");
        MDIparent.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MDIparentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MDIparentMouseClicked
        appointmentTab.initializeAppointments();
    }//GEN-LAST:event_MDIparentMouseClicked

    private void userPaneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userPaneActionPerformed
        MDIparent.setSelectedIndex(2);
    }//GEN-LAST:event_userPaneActionPerformed

    private void appointmentPaneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appointmentPaneActionPerformed
        MDIparent.setSelectedIndex(1);
    }//GEN-LAST:event_appointmentPaneActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        logout();
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        logout();
    }//GEN-LAST:event_formWindowClosing
    
    private void logout(){
        int result = JOptionPane.showConfirmDialog(null, "Are you sure you would like to logout? Any unsaved changes will be lost.", "Logout?", JOptionPane.ERROR_MESSAGE); 
        if (result == JOptionPane.YES_OPTION){
            this.setVisible(false);
            pLogin login = new pLogin();
            login.setVisible(true);
        } else {
            setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        }
    }
    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JTabbedPane MDIparent;
    public javax.swing.JTabbedPane appointment;
    private javax.swing.JButton appointmentPane;
    private javax.swing.JLabel greeting;
    private javax.swing.JPanel home;
    private javax.swing.JButton logoutButton;
    private javax.swing.JTabbedPane user;
    private javax.swing.JButton userPane;
    // End of variables declaration//GEN-END:variables
}