/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oodjassignment;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kishe
 */
public class PaymentForm extends javax.swing.JPanel {

    /**
     * Creates new form ResetPasswordForm
     */
    public PaymentForm() {
        initComponents();
        initializePayment();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        paymentList = new javax.swing.JTable();
        paymentLBL = new javax.swing.JLabel();
        printButton = new javax.swing.JButton();
        paymentDate_TXT = new com.toedter.calendar.JDateChooser();
        paymentDate_LBL = new javax.swing.JLabel();
        appointmentId_TXT = new javax.swing.JTextField();
        appointmentId_LBL = new javax.swing.JLabel();
        clearButton = new javax.swing.JButton();
        technicianId_TXT = new javax.swing.JTextField();
        technicianId_LBL = new javax.swing.JLabel();

        setBackground(new java.awt.Color(235, 215, 194));
        setPreferredSize(new java.awt.Dimension(900, 600));

        paymentList.setAutoCreateRowSorter(true);
        paymentList.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        paymentList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Payment Amount", "Date", "Manager ID", "Technician ID", "Appointment ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        paymentList.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(paymentList);

        paymentLBL.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        paymentLBL.setForeground(new java.awt.Color(0, 33, 88));
        paymentLBL.setText("Payments");

        printButton.setBackground(new java.awt.Color(0, 33, 71));
        printButton.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 16)); // NOI18N
        printButton.setForeground(new java.awt.Color(255, 255, 255));
        printButton.setText("Print to PDF");
        printButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButtonActionPerformed(evt);
            }
        });

        paymentDate_TXT.setDateFormatString("dd/MM/y");
        paymentDate_TXT.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        paymentDate_TXT.setEnabled(false);
        paymentDate_TXT.getCalendarButton().setEnabled(true);

        Calendar today = Calendar.getInstance();
        Date toDay = today.getTime();
        paymentDate_TXT.setMaxSelectableDate(toDay); // select until today
        paymentDate_TXT.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                paymentDate_TXTPropertyChange(evt);
            }
        });

        paymentDate_LBL.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        paymentDate_LBL.setForeground(new java.awt.Color(0, 33, 71));
        paymentDate_LBL.setText("Payment Date :");

        appointmentId_TXT.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        appointmentId_TXT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                appointmentId_TXTKeyReleased(evt);
            }
        });

        appointmentId_LBL.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        appointmentId_LBL.setForeground(new java.awt.Color(0, 33, 71));
        appointmentId_LBL.setText("Appointment ID :");

        clearButton.setBackground(new java.awt.Color(0, 33, 71));
        clearButton.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 16)); // NOI18N
        clearButton.setForeground(new java.awt.Color(255, 255, 255));
        clearButton.setText("Clear Filters");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        technicianId_TXT.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        technicianId_TXT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                technicianId_TXTKeyReleased(evt);
            }
        });

        technicianId_LBL.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        technicianId_LBL.setForeground(new java.awt.Color(0, 33, 71));
        technicianId_LBL.setText("Technician ID :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(paymentLBL)
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(paymentDate_LBL)
                            .addComponent(appointmentId_LBL))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(paymentDate_TXT, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(appointmentId_TXT, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(technicianId_LBL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(technicianId_TXT, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                        .addComponent(printButton, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(paymentDate_TXT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(appointmentId_TXT, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 3, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(paymentLBL, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(paymentDate_LBL, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGap(24, 24, 24)
                                        .addComponent(appointmentId_LBL))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(technicianId_TXT, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(technicianId_LBL)))
                                        .addGap(18, 18, 18)
                                        .addComponent(clearButton)))))
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(printButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(141, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void printButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButtonActionPerformed
        
    }//GEN-LAST:event_printButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        technicianId_TXT.setText("");
        appointmentId_TXT.setText("");
        paymentDate_TXT.setDate(null);
        initializePayment();
    }//GEN-LAST:event_clearButtonActionPerformed

    private void appointmentId_TXTKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_appointmentId_TXTKeyReleased
        String[] numbers = {"0", "1", "2", "3", "4", "5", "6", "7", "8", "9"};
        int numbersOnly = 0;
        
        for(int digit =0; digit < appointmentId_TXT.getText().length(); digit++){ //for each character in string
            for(int i =0; i < numbers.length; i++){ //check if matches with each digit
                if (appointmentId_TXT.getText().substring(digit, digit + 1).equals(numbers[i])){
                    numbersOnly++; // increment by 1
                }
            }
        }
        
        if (appointmentId_TXT.getText().length() != numbersOnly){
            JOptionPane.showMessageDialog(null, "The appointment id entered is invalid", "Only Numbers Allowed", JOptionPane.WARNING_MESSAGE);
            appointmentId_TXT.requestFocus();
        } else {
            filterPayment();
        }
    }//GEN-LAST:event_appointmentId_TXTKeyReleased

    private void paymentDate_TXTPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_paymentDate_TXTPropertyChange
        filterPayment();
    }//GEN-LAST:event_paymentDate_TXTPropertyChange

    private void technicianId_TXTKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_technicianId_TXTKeyReleased
        String[] numbers = {"0", "1", "2", "3", "4", "5", "6", "7", "8", "9"};
        int numbersOnly = 0;
        
        for(int digit =0; digit < technicianId_TXT.getText().length(); digit++){ //for each character in string
            for(int i =0; i < numbers.length; i++){ //check if matches with each digit
                if (technicianId_TXT.getText().substring(digit, digit + 1).equals(numbers[i])){
                    numbersOnly++; // increment by 1
                }
            }
        }
        
        if (technicianId_TXT.getText().length() != numbersOnly){
            JOptionPane.showMessageDialog(null, "The technician id entered is invalid", "Only Numbers Allowed", JOptionPane.WARNING_MESSAGE);
            technicianId_TXT.requestFocus();
        } else {
            filterPayment();
        }
    }//GEN-LAST:event_technicianId_TXTKeyReleased
    
    SimpleDateFormat loginDateFormatter = new SimpleDateFormat("dd/MM/yyyy");
    private void filterPayment(){
        //LOGIN LOG_T
        File payment = new File("src/db/payment_t.txt");
        
        try{         
        FileReader fr = new FileReader(payment);
        BufferedReader br = new BufferedReader(fr);
            
        DefaultTableModel model = (DefaultTableModel)paymentList.getModel();
        model.setRowCount(0); //clear table
        Object[] lines = br.lines().toArray();
        
        for(int i = 0; i < lines.length; i++){
            String[] row = lines[i].toString().split(":");
            if(paymentDate_TXT.getDate() != null && ( appointmentId_TXT.getText().equals("") == true ) && ( technicianId_TXT.getText().equals("") == true )){  // code to filter based on condition
                if(row[2].contains(loginDateFormatter.format(paymentDate_TXT.getDate())) == true){
                    model.addRow(row); //load data
                }
            }
            else if(paymentDate_TXT.getDate() == null && ( appointmentId_TXT.getText().equals("") == false ) && ( technicianId_TXT.getText().equals("") == true )){  // code to filter based on condition
                if(row[5].equals(appointmentId_TXT.getText()) == true){
                    model.addRow(row); //load data
                }
            }
            else if(paymentDate_TXT.getDate() == null && ( appointmentId_TXT.getText().equals("") == true ) && ( technicianId_TXT.getText().equals("") == false )){  // code to filter based on condition
                if(row[4].equals(technicianId_TXT.getText()) == true){
                    model.addRow(row); //load data
                }
            }
            else if(paymentDate_TXT.getDate() != null && ( appointmentId_TXT.getText().equals("") == false ) && ( technicianId_TXT.getText().equals("") == true )){  // code to filter based on condition
                if(row[2].contains(loginDateFormatter.format(paymentDate_TXT.getDate())) == true){
                    if(row[5].equals(appointmentId_TXT.getText()) == true){
                        model.addRow(row); //load data
                    }
                }
            }
            else if(paymentDate_TXT.getDate() != null && ( appointmentId_TXT.getText().equals("") == true ) && ( technicianId_TXT.getText().equals("") == false )){  // code to filter based on condition
                if(row[2].contains(loginDateFormatter.format(paymentDate_TXT.getDate())) == true){
                    if(row[4].equals(technicianId_TXT.getText()) == true){
                        model.addRow(row); //load data
                    }
                }
            }
            else if(paymentDate_TXT.getDate() == null && ( appointmentId_TXT.getText().equals("") == false ) && ( technicianId_TXT.getText().equals("") == false )){  // code to filter based on condition
                if(row[5].equals(appointmentId_TXT.getText()) == true){
                    if(row[4].equals(technicianId_TXT.getText()) == true){
                        model.addRow(row); //load data
                    }
                }
            }
            else if (paymentDate_TXT.getDate() != null && ( appointmentId_TXT.getText().equals("") == false ) && ( technicianId_TXT.getText().equals("") == false )) { // FILTER USING ALL
                if(row[5].equals(appointmentId_TXT.getText()) == true){
                    if(row[4].equals(technicianId_TXT.getText()) == true){
                        if(row[2].contains(loginDateFormatter.format(paymentDate_TXT.getDate())) == true){
                            model.addRow(row); //load data
                        }
                    }
                }
            }
            else { initializePayment(); }
            
        }
        } catch(FileNotFoundException ex){}
    }
    
    private void initializePayment(){
        //LOGIN LOG_T
        File payment = new File("src/db/payment_t.txt");
        
        try{         
        FileReader fr = new FileReader(payment);
        BufferedReader br = new BufferedReader(fr);
            
        DefaultTableModel model = (DefaultTableModel)paymentList.getModel();
        model.setRowCount(0); //clear table
        Object[] lines = br.lines().toArray();
        
        for(int i = 0; i < lines.length; i++){
            String[] row = lines[i].toString().split(":");
            model.addRow(row); //load data
        }
        } catch(FileNotFoundException ex){}
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel appointmentId_LBL;
    protected javax.swing.JTextField appointmentId_TXT;
    private static javax.swing.JButton clearButton;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel paymentDate_LBL;
    private com.toedter.calendar.JDateChooser paymentDate_TXT;
    private javax.swing.JLabel paymentLBL;
    static javax.swing.JTable paymentList;
    private static javax.swing.JButton printButton;
    private javax.swing.JLabel technicianId_LBL;
    protected javax.swing.JTextField technicianId_TXT;
    // End of variables declaration//GEN-END:variables
}
