/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oodjassignment;

import java.awt.Color;
import java.io.File;
import java.io.FileNotFoundException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Scanner;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
/**
 *
 * @author User
 */
public class pPayment extends javax.swing.JFrame {

    /**
     * Creates new form pFeedback1
     */
    public pPayment() {
        initComponents();
        AutoPaymentID();
        if (txtPaymentID.getText().equals("")){
                    txtPaymentID.setText("1");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTechnicianID = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblAppointmentID = new javax.swing.JLabel();
        txtPaymentID = new javax.swing.JTextField();
        txtAppointmentID = new javax.swing.JTextField();
        btnSend = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblPaymentID = new javax.swing.JLabel();
        txtTechnicianID = new javax.swing.JTextField();
        txtPaymentAmount = new javax.swing.JTextField();
        lblPaymentAmount = new javax.swing.JLabel();
        lblManagerID = new javax.swing.JLabel();
        txtManagerID = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AHHASC Payment");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lblTechnicianID.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        lblTechnicianID.setText("Technician ID");

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 0, 36)); // NOI18N
        jLabel2.setText("PAYMENT");

        lblAppointmentID.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        lblAppointmentID.setText("Appointment ID");

        txtPaymentID.setEnabled(false);
        txtPaymentID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPaymentIDActionPerformed(evt);
            }
        });
        txtPaymentID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPaymentIDKeyReleased(evt);
            }
        });

        txtAppointmentID.setEditable(false);
        txtAppointmentID.setFont(new java.awt.Font("Bahnschrift", 0, 11)); // NOI18N
        txtAppointmentID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAppointmentIDKeyReleased(evt);
            }
        });

        btnSend.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        btnSend.setText("Send");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblPaymentID.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        lblPaymentID.setText("Payment ID");

        txtTechnicianID.setEditable(false);
        txtTechnicianID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTechnicianIDActionPerformed(evt);
            }
        });
        txtTechnicianID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTechnicianIDKeyReleased(evt);
            }
        });

        txtPaymentAmount.setEditable(false);
        txtPaymentAmount.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPaymentAmountFocusLost(evt);
            }
        });
        txtPaymentAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPaymentAmountActionPerformed(evt);
            }
        });
        txtPaymentAmount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPaymentAmountKeyReleased(evt);
            }
        });

        lblPaymentAmount.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        lblPaymentAmount.setText("Payment Amount");

        lblManagerID.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        lblManagerID.setText("Manager ID");

        txtManagerID.setEditable(false);
        txtManagerID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtManagerIDActionPerformed(evt);
            }
        });
        txtManagerID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtManagerIDKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(24, 24, 24)
                                            .addComponent(lblPaymentID)
                                            .addGap(41, 41, 41))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(lblPaymentAmount)
                                            .addGap(33, 33, 33)))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtPaymentAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtPaymentID, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblManagerID)
                                    .addGap(33, 33, 33)
                                    .addComponent(txtManagerID, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblAppointmentID)
                                    .addComponent(lblTechnicianID)
                                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtTechnicianID, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtAppointmentID, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(80, 80, 80)
                                        .addComponent(btnSend, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jLabel2)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPaymentID)
                    .addComponent(txtPaymentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPaymentAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPaymentAmount))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblManagerID)
                    .addComponent(txtManagerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTechnicianID)
                    .addComponent(txtTechnicianID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAppointmentID)
                    .addComponent(txtAppointmentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSend, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPaymentIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPaymentIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPaymentIDActionPerformed

    private void txtPaymentIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPaymentIDKeyReleased
        String value = txtPaymentID.getText();
        int l = value.length();
        if ((evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') || evt.getKeyChar() <= '-' ) {
            if(l <0 || l>12){
                JOptionPane.showMessageDialog(null, "Invalid Length");
                txtPaymentID.setText("");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please enter only numbers");
            txtPaymentID.setText("");
        }
    }//GEN-LAST:event_txtPaymentIDKeyReleased

    private void txtAppointmentIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAppointmentIDKeyReleased
        String value = txtAppointmentID.getText();
        int l = value.length();
        if ((evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') || evt.getKeyChar() <= '-' ) {
            if(l <0 || l>12){
                JOptionPane.showMessageDialog(null, "Invalid Length");
                txtAppointmentID.setText("");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please enter only numbers");
            txtAppointmentID.setText("");
        }
    }//GEN-LAST:event_txtAppointmentIDKeyReleased
    
    String managerID, technicianID, appointmentID, paymentID,creationDate;
    double paymentAmount;
    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed

        try{

            Calendar currentDate = Calendar.getInstance();
            SimpleDateFormat datef = new SimpleDateFormat("dd/MM/yyyy");

            creationDate = datef.format(currentDate.getTime());
            paymentID = txtPaymentID.getText(); 
            paymentAmount = Double.parseDouble(txtPaymentAmount.getText());
            managerID = txtManagerID.getText();
            technicianID = txtTechnicianID.getText();
            appointmentID = txtAppointmentID.getText();

            IsEmpty = true;
            CheckEmpty();

            if (IsEmpty == false){
                // Write the name to the file.
                payment py = new payment( paymentID ,paymentAmount, creationDate, managerID, technicianID, appointmentID);
                py.addPayment(paymentID ,paymentAmount, creationDate,managerID, technicianID, appointmentID);
                
                //JOptionPane.showMessageDialog(null, "Adding Succesful!");
                ClearText();
                AutoPaymentID();
   

                JOptionPane.showMessageDialog(null, py.toString(), "Adding Succesful!",  JOptionPane.PLAIN_MESSAGE );
                returnToMenu();
            }else {
                JOptionPane.showMessageDialog(null, "Make sure all input fields are properly keyed in");

            }

        } catch(Exception e){
            JOptionPane.showMessageDialog(null, "An error occured!");
        }

    }//GEN-LAST:event_btnSendActionPerformed

    private void txtTechnicianIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTechnicianIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTechnicianIDActionPerformed

    private void txtTechnicianIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTechnicianIDKeyReleased
        String value = txtTechnicianID.getText();
        int l = value.length();
        if ((evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') || evt.getKeyChar() <= '-' ) {
            if(l <0 || l>12){
                JOptionPane.showMessageDialog(null, "Invalid Length");
                txtTechnicianID.setText("");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please enter only numbers");
            txtTechnicianID.setText("");
        }
    }//GEN-LAST:event_txtTechnicianIDKeyReleased

    private void txtPaymentAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPaymentAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPaymentAmountActionPerformed

    private void txtPaymentAmountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPaymentAmountKeyReleased
        String value = txtPaymentAmount.getText();
        int l = value.length();
        if ((evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') || evt.getKeyChar() <= '-'  || evt.getKeyChar() <= '.') {
            if(l <0 || l>12){
                JOptionPane.showMessageDialog(null, "Invalid Length");
                txtPaymentAmount.setText("");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please enter only numbers");
            txtPaymentAmount.setText("");
        }
    }//GEN-LAST:event_txtPaymentAmountKeyReleased

    private void txtManagerIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtManagerIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtManagerIDActionPerformed

    private void txtManagerIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtManagerIDKeyReleased
        String value = txtTechnicianID.getText();
        int l = value.length();
        if ((evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') || evt.getKeyChar() <= '-' ) {
            if(l <0 || l>12){
                JOptionPane.showMessageDialog(null, "Invalid Length");
                txtTechnicianID.setText("");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please enter only numbers");
            txtTechnicianID.setText("");
        }
    }//GEN-LAST:event_txtManagerIDKeyReleased

    private void txtPaymentAmountFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPaymentAmountFocusLost
        if(txtPaymentAmount.getText().contains(":")){
            JOptionPane.showMessageDialog(null, "Invalid symbol ':' used ");
            txtPaymentAmount.setText("");
       } 
    }//GEN-LAST:event_txtPaymentAmountFocusLost

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        returnToMenu();
    }//GEN-LAST:event_formWindowClosing

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        returnToMenu();
    }//GEN-LAST:event_btnBackActionPerformed
      
    private void returnToMenu(){
         this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
         
         this.setVisible(false);
         
         AHHASC_Manager managerInterface = new AHHASC_Manager();
         managerInterface.setVisible(true);
     }
    
    boolean IsEmpty;
    private void CheckEmpty(){
        
        //NOT COMPLETE
        if(txtPaymentID.getText().equals("")){
           IsEmpty = true;
           defaultLabelColor();
           lblPaymentID.setForeground(Color.red);
        }else if(txtPaymentAmount.getText().equals("")){
           IsEmpty = true;
           defaultLabelColor();
           lblPaymentAmount.setForeground(Color.red);
        }else if(txtManagerID.getText().equals("")){
           IsEmpty = true;
           defaultLabelColor();
           lblManagerID.setForeground(Color.red);
        }else if(txtTechnicianID.getText().equals("")){
           IsEmpty = true;
           defaultLabelColor();
           lblTechnicianID.setForeground(Color.red);
        }else if(txtAppointmentID.getText().equals("")){
           IsEmpty = true;
           defaultLabelColor();
           lblAppointmentID.setForeground(Color.red);
        }else {
            IsEmpty = false;
           defaultLabelColor();
        }
       
    }
    
    private void defaultLabelColor(){
            lblPaymentID.setForeground(Color.BLACK);
            lblPaymentAmount.setForeground(Color.BLACK);
            lblManagerID.setForeground(Color.BLACK);
            lblTechnicianID.setForeground(Color.BLACK);
            lblAppointmentID.setForeground(Color.BLACK);
    }
    
    private void ClearText(){
           txtPaymentID.setText("");
           txtPaymentAmount.setText("");
           txtManagerID.setText("");
           txtAppointmentID.setText("");
           txtTechnicianID.setText("");
           defaultLabelColor();
           
    }
    
     private void AutoPaymentID(){
        //DecimalFormat dc = new DecimalFormat("000000");
        // This is to ensure the entire method have access to the selectedID array
        String[] selectedID = null;
        try {
            String dir = System.getProperty("user.dir") + "\\src\\DB\\";
            // For debugging purpose only
            // JOptionPane.showMessageDialog(null, bID);
            File customertxt = new File(dir + "payment_t.txt");
            Scanner inputFile;
            try {
                inputFile = new Scanner(customertxt);
                // Read lines from the file until no more are left.
                while (inputFile.hasNext())
                {
                   // Read the next line.
                   String bEntry = inputFile.nextLine();
                   // Split the line by using the delimiter ":" (semicolon) and store into array.
                   selectedID = bEntry.split(":");
                }
                inputFile.close();
                int newCustomerID = Integer.parseInt(selectedID[0]) + 1;
                txtPaymentID.setText(String.valueOf(newCustomerID));
                
                System.out.println(newCustomerID);
                
                
            } catch (FileNotFoundException ex) {
              
            }
        }
        catch (Exception ex) {
   
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSend;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAppointmentID;
    private javax.swing.JLabel lblManagerID;
    private javax.swing.JLabel lblPaymentAmount;
    private javax.swing.JLabel lblPaymentID;
    private javax.swing.JLabel lblTechnicianID;
    protected javax.swing.JTextField txtAppointmentID;
    protected javax.swing.JTextField txtManagerID;
    protected javax.swing.JTextField txtPaymentAmount;
    private javax.swing.JTextField txtPaymentID;
    protected javax.swing.JTextField txtTechnicianID;
    // End of variables declaration//GEN-END:variables
}
